### ISSUE TITLE
Multicast sample has invalid permissions.

### ISSUE THREAD

**Issue by mckoss** [GoogleChrome/chrome-app-samples#119]
On Chrome version 27 (stable), I can't get this sample to load properly.

    Could not load extension from '/Users/<username>/src/chrome-app-samples/multicast'. Invalid value for 'permissions[socket]'.

If I remove the socket['udp-multicast-membership'] permission, the app will load (though I don't think it works properly).

**Comment by beaufortfrancois** [comment]
Multicast sample has been updated to use the new chrome.sockets.udp API.
Please reopen if you're still experiencing any issue.
