### ISSUE TITLE
IOIO Example Doesn't Work

### ISSUE THREAD

**Issue by Fleker** [GoogleChrome/chrome-app-samples#263]
As in the previous issue #262, I downloaded the IOIO Sample from the Web Store and there's an immediate bug which prevents the app from going further:

`Uncaught TypeError: Cannot read property 'getDevices' of undefined main.js:86`

    
    Google Chrome	37.0.2062.3 (Official Build 279868) dev-m
    OS	                Windows

**Comment by beaufortfrancois** [comment]
From http://crbug.com/392654 _We don't have any plans at this time for extending the chrome.bluetooth JS API, or supporting LE Peripheral mode on Chromebooks_
