### ISSUE TITLE
[usb/knob] 'Get permissions' error

### ISSUE THREAD

**Issue by DanMcLaughlin** [GoogleChrome/chrome-app-samples#328]
Running on Win7 64 bit, Chrome version 38.0.2125.101

The version from the App doesn't work with a Griffen puck (just shows a blank window, nothing turns). Debugging the code from the repo shows I'm getting a thrown error on line 87 of knob.js when the ask permission button is pushed

"Uncaught TypeError: Cannot read property 'addEventListener' of null

I'm learning how to control USB devices via Chrome JavaScript so unfortunately can't offer any further help as to what the problem is.

**Comment by beaufortfrancois** [comment]
Hello @DanMcLaughlin,
Do you still see the error?

**Comment by DanMcLaughlin** [comment]
Yeah, but I've moved on to other projects, go ahead and close it, thanks.
