### ISSUE TITLE
mDNS announcement

### ISSUE THREAD

**Issue by debugger22** [GoogleChrome/chrome-app-samples#331]
This is not an issue.

We have an example for mDNS browser which is really good. Is it possible to implement mDNS announcement just like Apple Bonjour or Android NSD in Chrome packaged apps? I can't find anything related to this in the documentation and there are no resources on the internet too.

Any help would be appreciable.

**Comment by beaufortfrancois** [comment]
You might want to follow discussion at https://code.google.com/p/chromium/issues/detail?id=426500 to get updates about `chrome.mdns`
