### ISSUE TITLE
How to automate App testing

### ISSUE THREAD

**Issue by emmanuelmillionaer** [GoogleChrome/chrome-app-samples#348]
Hi,

how would you automate App testing?

I tried to start chromedriver in App-Modus but it won't work:
`Selenium::WebDriver.for :chrome, :args => ["--app-id=olddgoefnehjeogjhpcpolcnnifnglkp"]`

Thanks for your ideas and suggestions!

**Comment by beaufortfrancois** [comment]
According to https://sites.google.com/a/chromium.org/chromedriver/extensions, you could do that:

```
ChromeOptions options = new ChromeOptions();
options.addArguments("load-extension=/path/to/extension");
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(ChromeOptions.CAPABILITY, options);
ChromeDriver driver = new ChromeDriver(capabilities);
```
