### ISSUE TITLE
need an example of scanning with bluetoothLowEnergy

### ISSUE THREAD

**Issue by monteslu** [GoogleChrome/chrome-app-samples#350]
The current Bluetooth Low-Energy Device Information Service Demo requires that the client already knows about the device.  Bluetooth 4.0 (BLE) provides the ability to scan nearby devices based on a service UUID, and then connect and query characteristics and descriptors.

**Comment by XhuaChen** [comment]
+1

**Comment by sandeepmistry** [comment]
+1

**Comment by beaufortfrancois** [comment]
The "Start Discovery" button has actually been added previously to this bluetooth sample but not published in the Web Store. 
I've just bumped the manifest app version and updated the webstore item at https://chrome.google.com/webstore/detail/dblimghcclaakknbpajckcamddhjaaai/

Thank you for raising this issue!

**Comment by monteslu** [comment]
The problem is that it is still using bluetooth 3.0 APIs.
Other libraries such as Noble for Node, or iOS and Android BLE libraries allow you to scan by service UUID.

This example app is calling chrome.bluetooth.getDevices() which only lists things that are already connected or saved to the OS.   As far as I can tell, the discovery toggle handler in the code only logs errors if it finds them..

**Comment by monteslu** [comment]
Should reopen this issue

**Comment by beaufortfrancois** [comment]
I'm not sure about BT 3.0 APIs but from what I can read at https://developer.chrome.com/apps/bluetooth#method-startDiscovery,

_Start discovery. Newly discovered devices will be returned via the onDeviceAdded event. Previously discovered devices already known to the adapter must be obtained using getDevices and will only be updated using the |onDeviceChanged| event if information about them changes._

Maybe @oahziur can help us there.

**Comment by beaufortfrancois** [comment]
You're actually right, the battery-service-demo and heart-rate-sensor bluetooth samples use onDeviceAdded to gather new discovered devices.
Therefore, I will add it.

Thank you Luis!

**Comment by beaufortfrancois** [comment]
Hey Luis,
I've just created a Pull Request https://github.com/GoogleChrome/chrome-app-samples/pull/353 that you might want to try before it's getting reviewed.
Please let me know what you think.

**Comment by beaufortfrancois** [comment]
PR has been accepted and Webstore Item published at https://chrome.google.com/webstore/detail/device-information-servic/dblimghcclaakknbpajckcamddhjaaai
Please reopen the issue if there's something wrong.
