### ISSUE TITLE
Calculator Issues

### ISSUE THREAD

**Issue by stacyveazey** [GoogleChrome/chrome-app-samples#352]
I need help with my calculator app. It will not show full calculator. I have to move from left to right to see the numbers as I'm typing. I can not expand the calculator and ctrl +- does not help. I do not know how to fix this problem. My Chromebook came like this. I did not do anything to it. Thanks.

**Comment by beaufortfrancois** [comment]
Hello!
Can you share a screenshot with us?

**Comment by stacyveazey** [comment]
I don't know how to do that either. The calculator is just cut short you can only see half of it at a time.

**Comment by beaufortfrancois** [comment]
It's actually quite easy: http://www.omgchrome.com/take-screenshot-chromebook-chromeos/

**Comment by beaufortfrancois** [comment]
Please reopen this issue if you're still seeing this issue.
