### ISSUE TITLE
InApp Payments: TOKEN_MISSING_ERROR

### ISSUE THREAD

**Issue by Alex-1966** [GoogleChrome/chrome-app-samples#354]
I recently integrated inapp payments in my chrome app, based on the sample given here.

For testing purpose i just implemented this function

google.payments.inapp.getSkuDetails({
	  'parameters': {'env': 'prod'},
	  'success': listtems,
	  'failure': errorSkuDetails
	});

this ends up in calling the failure function with following response:

errorType: "TOKEN_MISSING_ERROR"

Didn't found any information about a token parameter. What token is meant? Thx for any advice.

**Comment by Alex-1966** [comment]
i solved the issue on my own by adding following configs to my manifest.json and upload the updated version to chrome webstore:

"permissions": [
	  "https://www.googleapis.com/",
	],
"oauth2": {
"client_id": "xxx.apps.googleusercontent.com",
		"scopes": [
		  "https://www.googleapis.com/auth/chromewebstore.readonly"
		]
	  }

**Comment by jktaylor** [comment]
I tried this route and did not work for me.  What did work was signing into google chrome.  I did not know you could actually sign into google chrome.  I was signed into google using chrome, but not signed into google chrome itself.  I signed up for the web store api and put in client keys into my manifest and tried all sorts of different things that were not necessary.  Signing into google chrome is never mentioned in the developer documentation.

**Comment by datermine** [comment]
I have users that frequently experience this as well. Is there an official solution?
