### ISSUE TITLE
Identity sample has broken links to source code

### ISSUE THREAD

**Issue by brawer** [GoogleChrome/chrome-app-samples#356]
The sample app for the Chrome Identity API has broken links to source code on GitHub.

For example, here's one of the in-app links (which gives a 404):
https://github.com/GoogleChrome/chrome-app-samples/tree/master/identity/identity.js#L44-L87

Instead of the above, the correct link seems to be this:
https://github.com/GoogleChrome/chrome-app-samples/blob/master/samples/identity/identity.js#L44-L87

**Comment by beaufortfrancois** [comment]
Hello Sascha,

You're right, I'm gonna fix URL at https://github.com/GoogleChrome/chrome-app-samples/blob/eda97b55e66198fcf889eb9a4e7e2e755c92bdfe/samples/identity/sample_support/show_snippets.js#L69

**Comment by brawer** [comment]
Oh, I'll gladly send you a patch... just a few minutes, pull request is coming.

**Comment by beaufortfrancois** [comment]
Thanks Sascha,

It looks like this file is pulled from somewhere else: https://github.com/GoogleChrome/chrome-app-samples/blob/eda97b55e66198fcf889eb9a4e7e2e755c92bdfe/samples/identity/sample_support/README.md

*ATTENTION contributors: this directory (sample_support) should not be changed. It is automatically updated and should not contain anything that is specific to this sample.*

**Comment by brawer** [comment]
@mangini might know the upstream source for chrome-app-samples/samples/identity/sample_support?

**Comment by mangini** [comment]
Fixed, thanks!

**Comment by beaufortfrancois** [comment]
Thank you Renato!
Just updated webstore item at https://chrome.google.com/webstore/detail/identity-api-sample/oficlfehfenioickohognhdhmmcpceil
