### ISSUE TITLE
samples/bluetooth-samples/device-info-demo not working on MacOSX 10.9

### ISSUE THREAD

**Issue by biafra23** [GoogleChrome/chrome-app-samples#357]
When I hit the "start discovery" button nothing is detected although there are several BLE devices around that can be detected with LightBlue. 

Is the API even supported on MacOSX 10.9/10.10? Is this supposed to work anywhere? Linux? Windows?

What is the status of the Implementation of the API?

**Comment by beaufortfrancois** [comment]
BLE is not yet supported on Mac OS even though the chromium team is working on it as we speak. You can follow the work in progress at https://code.google.com/p/chromium/issues/detail?id=449682

**Comment by biafra23** [comment]
Thanks for the clarification regarding MacOSX!
Is it supported on Linux or WIndows?
