### ISSUE TITLE
Where is chrome.hid.getUserSelectedDevices?

### ISSUE THREAD

**Issue by thealexbaron** [GoogleChrome/chrome-app-samples#360]
In the usb api there is an api for `chrome.usb.getUserSelectedDevices`. Is `chrome.hid.getUserSelectedDevices` coming soon?

**Comment by reillyeon** [comment]
It was assumed in the development of `chrome.usb.getUserSelectedDevices` that there would eventually be a version for the `chrome.hid` API as well. You are the first person to ask for it. I will file a bug against Chromium to track this feature request. Can you give an idea of the kind of application you would write using this API?

**Comment by thealexbaron** [comment]
We are writing a shipping web app that will read weight scales and possibly barcode readers. We are currently adding scales manually via manifest.json, but we have a large userbase and we aren't sure of all of the possibilities of scales.

**Comment by reillyeon** [comment]
The `chrome.usb.getUserSelectedDevices` interface implements filters based on USB device class and protocol numbers. Is there a filter (such as HID usage or usage page) that would catch all the devices you are interested in or will the user need to be presented with a list of all connected devices?

**Comment by reillyeon** [comment]
Also, do these HID devices often have a serial number exposed over the USB bus?

**Comment by willconantrs** [comment]
Yes, both scales and barcode scanners have specific HID usage pages. For instance, our scales are all on either

    {usage: 1, usagePage: 141}

or

    {usage: 32, usagePage: 141}

Most of the scales that I have tried no not seem to expose a serial number.

**Comment by reillyeon** [comment]
Thank you for all this information. I've filed a Chromium bug to track this feature implementation: https://code.google.com/p/chromium/issues/detail?id=457899
