### ISSUE TITLE
Customize Print Preview

### ISSUE THREAD

**Issue by unDemian** [GoogleChrome/chrome-app-samples#364]
Hello,
Is there any way to customize Print Preview Dialog or to use a custom one /  some kind of print api because the current window is not really optimized for touch screens.
Thanks

**Comment by beaufortfrancois** [comment]
Print Preview Dialog is not customizable for now.
You may want to file a feature request at crbug.com/new so that the chromium team knows about this issue. See https://code.google.com/p/chromium/issues/list?q=label:Cr-UI-Browser-PrintPreview for all  feedback related to the print preview dialog.
