### ISSUE TITLE
printing-support

### ISSUE THREAD

**Issue by vikrantpogula** [GoogleChrome/chrome-app-samples#373]
Nice set of examples here :+1: ! I don't know where exactly to ask this but is there a way to print from a packaged/hosted app without showing the print popup ? (while retaining capability to change destination, copies etc.)

The primary concern being that javascript in the background gets paused during the print popup (which hampers background service methods).

Please let me know if anyone has any ideas on how to try and implement this ?

**Comment by beaufortfrancois** [comment]
Using `window.print` in a chrome app will always triggered the print popup for sure. You might want to have a look at https://developer.chrome.com/apps/printerProvider but it's not exactly what you're asking though.
