### ISSUE TITLE
Is it possible to add an example to connect with a Bluetooth 2.0 device using serial profile.

### ISSUE THREAD

**Issue by jabrena** [GoogleChrome/chrome-app-samples#382]
Hi,

I would like to learn using Serial API, but my bluetooth devices is not BLE.
Can you show a micro example.

Many thanks in advance.

Juan Antonio

**Comment by reillyeon** [comment]
You can use the serial API to connect to any Bluetooth device that uses the serial profile. Just make sure that the device is paired and it should show up as an available serial port. Setup will depend on your host operating system.

**Comment by jabrena** [comment]
What example do you recommend to learn to use serial API?

**Comment by reillyeon** [comment]
This [example](https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/serial/ledtoggle) provides a simple application and Arduino sketch to try out the serial API. Of course if you are writing an app to work with your own Bluetooth serial device you will need to learn about the commands that it expects and I cannot provide guidance there.

**Comment by jabrena** [comment]
Many thanks, I am trying to connect with a EV3 brick.
Now, I connect, but I have to find how to send a direct command.

Many thanks for the support.

I will inform if I get some result.

Juan Antonio

**Comment by jabrena** [comment]
Hi, I am near but I have a micro problem.

I would like to send this array of bytes:
var cmd = [0x06 0x00 0x00 0x03 0x0B 0x02 0xF4 0x01 ];

but in the example from this project:
https://github.com/GoogleChrome/numberhtml5-app/blob/master/app/static/js/serial.js

Exist a function to convert:

 /* the arraybuffer is interpreted as an array of UTF-8 (1-byte Unicode chars) */
  var ab2str=function(buf) {
    var bufView=new Uint8Array(buf);
    var unis=[];
    for (var i=0; i<bufView.length; i++) {
      unis.push(bufView[i]);
    }
    return String.fromCharCode.apply(null, unis);
  };

but when I try to use this function, I get the following error:
Uncaught TypeError: str.charCodeAt is not a function
bufView[i]=str.charCodeAt(i); <- In this part.

how to send an array of bytes using Serial?

Many thanks in advance.

**Comment by reillyeon** [comment]
You need to construct an ArrayBuffer containing those bytes. The easiest way to do it from an array of integers is to create a Uint8Array and then get the underlying ArrayBuffer stored in the "buffer" attribute like this:

    var buffer = new Uint8Array([0x06, 0x00, 0x00, 0x03, 0x0B, 0x02, 0xF4, 0x01]).buffer;

**Comment by jabrena** [comment]
So, the idea is to execute this method in this way:

connection.send(buffer);

isn't it?

**Comment by reillyeon** [comment]
Yes.
