### ISSUE TITLE
Convert webserver sample to sockets.tcpServer

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/chrome-app-samples#384]
See https://developer.chrome.com/apps/app_network

**Comment by lostsource** [comment]
Not sure if this is the right place to point this out but I believe there are some errors in the examples at https://developer.chrome.com/apps/app_network

- On the last line of the `onAccept` function `setPaused` is missing the `socketId` argument
- The 'Sending Data' example under the 'Using UDP' section is missing a call to `chrome.sockets.udp.bind` before calling the `send` method. (as stated in [documentation](https://developer.chrome.com/apps/sockets_udp#method-send))

**Comment by beaufortfrancois** [comment]
It is the right place and you've already submitted a PR ;)
Thanks!
