### ISSUE TITLE
Not necessarily an issue

### ISSUE THREAD

**Issue by JacobEdward010** [GoogleChrome/chrome-app-samples#386]
https://github.com/GoogleChrome/chrome-app-samples/blob/master/samples/serial/espruino/main.js

I'm just curious how a connection is verified with the external device when you use 

serial.connect(path, this.onConnectComplete.bind(this))

I get that there is a callback function that will throw a connection failure if there isn't a object passed back as an argument, but what has to happen on the other end for there to be a successful connection?  Just a closed circuit of any kind or does a microcontroller have to give a handshake or something?

**Comment by reillyeon** [comment]
The connection is not verified with the external device. There's no standard "handshake" for serial connections. serial.connect is successful if Chrome successfully opens the serial port and configures it with the given parameters. A device doesn't even have to be connected on the other end.

**Comment by JacobEdward010** [comment]
Would you know how I might be able to create an ArrayBuffer to assign true binary values (or if chrome.serial.send() will be able to accept anything other than an ArrayBuffer)?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/setInt8

**Comment by reillyeon** [comment]
I don't understand what you mean by "true binary values." The documentation you linked to describes how to set individual bytes of an ArrayBuffer which is likely what you want.

I suggest taking questions like this to StackOverflow.
