### ISSUE TITLE
Can't see device information for Wahoo Fitness Bluetooth LE Balance Scale

### ISSUE THREAD

**Issue by davidthewatson** [GoogleChrome/chrome-app-samples#388]
I'm running the code here on Chrome 42 on Mac OS X 10.10:

https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/bluetooth-samples/device-info-demo

but after starting discovery, I never see any connected devices. I have a Wahoo Fitness Balance Scale that's BTLE but I'm not sure if there's something else I need to do to get it to talk. 

The device is functional over BTLE as I can see it on the light blue bluetooth debugging app on my iphone. I've tried to figure out if it responds to the 180a device information block, but I'm not sure.

Thanks!

**Comment by beaufortfrancois** [comment]
Bluetooth Low Energy only works on Chrome OS for now.
You might want to follow https://code.google.com/p/chromium/issues/detail?id=449682 to keep track of the work the chromium team is doing on Mac OS.
