### ISSUE TITLE
Broken Links from Chrome Web Store to Github Repo 

### ISSUE THREAD

**Issue by jacobmiller** [GoogleChrome/chrome-app-samples#389]
The [detail page](https://github.com/GoogleChrome/chrome-app-samples/tree/master/gdrive) on the CWS has 2 404's, both "from Chrome App Samples" under the title & the "Website" link in the description point to ["https://github.com/GoogleChrome/chrome-app-samples/tree/master/gdrive"](https://github.com/GoogleChrome/chrome-app-samples/tree/master/gdrive) instead of [https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/gdrive](https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/gdrive)

**Comment by beaufortfrancois** [comment]
Thank you really much!
I've just updated it the CWS page at https://chrome.google.com/webstore/detail/drive-sample/jpabeekbjicamajjcfejnochhmlbpgjh
