### ISSUE TITLE
Messaging sample extension in Chrome web store uses deprecated call

### ISSUE THREAD

**Issue by francislavoie** [GoogleChrome/chrome-app-samples#390]
Error in event handler for runtime.onMessageExternal: ReferenceError: webkitNotifications is not defined

The code in the repo seems updated though.

**Comment by beaufortfrancois** [comment]
Thank you so much Francis! I've updated CWS items:
https://chrome.google.com/webstore/detail/sample-messaging-extensio/ihhkahhkmiddbnfhlglocakcdfbgddkj
https://chrome.google.com/webstore/detail/sample-messaging-app1/mcfaknmahgbmjlbondlciokappnnjbnf
https://chrome.google.com/webstore/detail/sample-messaging-app2/hdligeegpimhdjepakblhneiekccbhol
