### ISSUE TITLE
Add tls enabled connection to the webserver sample

### ISSUE THREAD

**Issue by tejohnso** [GoogleChrome/chrome-app-samples#393]
Would be nice to have a reference implementation for TLS.

**Comment by tejohnso** [comment]
Implemented a sample that is working in Lynx and cUrl.  
https://github.com/Rise-Vision/chrome-app-tls-server

**Comment by beaufortfrancois** [comment]
Woo! That's pretty cool of you!
However, it seems to big to be a simple sample. 

How about I add a reference to your GitHub repository in https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/webserver ?

**Comment by tejohnso** [comment]
Sounds good :+1:

**Comment by beaufortfrancois** [comment]
Thanks! Check out https://github.com/GoogleChrome/chrome-app-samples/commit/bd973df6ac86520be3620380007387cf3031b280
