### ISSUE TITLE
Update chrome.hid sample to use chrome.hid.getUserSelectedDevices API

### ISSUE THREAD

**Issue by reillyeon** [GoogleChrome/chrome-app-samples#396]
Updating the HID sample app to use this new API (about to land in dev channel) will allow developers to try out the HID API with their devices without having to modify the app manifest to include permission for their device.

**Comment by beaufortfrancois** [comment]
If that's ok with you, I'll submit a PR since https://codereview.chromium.org/1115213004 has been accepted and I'll be glad if you can review it.

**Comment by reillyeon** [comment]
Go right ahead!

**Comment by beaufortfrancois** [comment]
I'll close this issue since all PR have been merged.
