### ISSUE TITLE
All links to posterous are broken

### ISSUE THREAD

**Issue by tezzutezzu** [GoogleChrome/chrome-app-samples#399]
ie. https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/serial/ledtoggle

has a broken link in its readme

**Comment by beaufortfrancois** [comment]
Thank you so much!
I've updated https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/serial/ledtoggle and https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/servo
