### ISSUE TITLE
Endpoint for usb printer

### ISSUE THREAD

**Issue by RimaSGit** [GoogleChrome/chrome-app-samples#400]
How do I get the endpoint for my usb printer?
I do have chrome.usb.listInterfaces which has numerous interfaces with bulk endpoints. Which one do I use for my usb printing and do i use the exact address obtained from listInterfaces or do I need to convert that endpoint address?

**Comment by reillyeon** [comment]
This information is different for every printer make and model and so far you've never said what hardware you have. If you don't have documentation for the printer or are willing to take the time to reverse engineer it you will not have much success getting it to work.

**Comment by RimaSGit** [comment]
I am using HP OfficeJet printer.

**Comment by reillyeon** [comment]
Okay, that's a start. The USB label printer example code you've been trying to use won't work for that printer because it is not a label printer. You will need to find documentation on the USB commands supported by that printer. I cannot help you there. Best of luck.

**Comment by RimaSGit** [comment]
PCLm

**Comment by RimaSGit** [comment]
PCLm
