### ISSUE TITLE
chrome app sending data using tcp socket crashes after 20 hours

### ISSUE THREAD

**Issue by zhaojun12** [GoogleChrome/chrome-app-samples#403]
Hi all, i write a chrome app which sends 10,000,000 bytes data using tcp socket each time and does this once an hour.

following is the code
```
var data = new ArrayBuffer(10000002);
var dataView = new Uint8Array(data);
for(var i=0; i<10000000; i++){
    dataView[i] = 16 + Math.round(Math.random() * 200);
}
dataView[10000000] = 240;
dataView[10000001] = 255;
tcp_socket.send(this.socketId, data, function(sendInfo){
    console.log("send to server with length " + sendInfo.bytesSent);
    delete dataView;
    delete data;
});
```
but after runing 20 hours, the app crashes; i have tried many times, it crashes all the time.

i have no idea why this happens, thanks.

**Comment by beaufortfrancois** [comment]
Can you share a minimalistic app where we can reproduce the issue?
Which platform are you running on?
Do you wake up your app with _chrome.alarms_ every hour?

**Comment by zhaojun12** [comment]
Thanks for your reply.
Yes, of cource. the attachment file is the app's simplified code for brevity.
This app is running Windows XP SP3 with 1G RAM, latest Chrome Version 43.0.2357; 
I do not use chrome.alarms to wake my app, instead i use setInterval function.
This app is used to measurement link performance between your PC and our server, such as bandwidth, packet loss. The result can be seen in the debug tool using console.log.
The app connects with two servers using tcp socket, one is controller, the other is server.
every hour the app sends start message to the controller, the controller will tell the app to test with which server; the app then will send 9,000,000 bytes data using tcp socket to the server, the server will calculate the bandwidth and packet loss.
Line 71, 137, 155, 196 in deamon.js  is the main part of the app.
the app will crash after running 20 hours approximately, cannot be restarted; after reboot the computer or change the code 9,000,000 to smaller size, it will restart successfully.
thanks.

Zhao Jun

Date: Mon, 22 Jun 2015 05:42:23 -0700

**Comment by beaufortfrancois** [comment]
Attachment files are not supported in GitHub emails. 
Do you mind sharing the code with a URL?

Moreover, you might want to switch to [chrome.alarms](https://developer.chrome.com/apps/alarms) for this specific behaviour. Something like this below should work:

```js
chrome.alarms.create('hello', {periodInMinutes: 60});
chrome.alarms.onAlarm.addListener(function() {
  // measurement link performance
});

**Comment by zhaojun12** [comment]
@François Beaufort
Thanks for your advice.
i have figured out the reason why the app crashes after running 20 hours long.
there is nothing wrong with google chrome app tcp socket api.
it is because a third lib i have used in the app which consumes too much RAM and CPU resources. After modifying the code, the app has running one and half days, and is still running.
Thanks!

Zhao Jun

Date: Thu, 25 Jun 2015 04:38:34 -0700

**Comment by beaufortfrancois** [comment]
Glad to hear that!
