### ISSUE TITLE
Running locally connection lost

### ISSUE THREAD

**Issue by danjpalmer** [GoogleChrome/chrome-app-samples#405]
Hi,

I'm trying to get this running locally, outside of the Chrome App Store, but I keep getting a "connection lost" message. The port it's attempting to connect to is free, so that's not the problem.

Any troubleshooting tips would be greatly appreciated!

Thanks

**Comment by beaufortfrancois** [comment]
Could you tell us which chrome app sample you're having issues with?

**Comment by danjpalmer** [comment]
My apologies. It was this example: https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/websocket-server

**Comment by danjpalmer** [comment]
Hi Beaufortfrancois, just wanted to follow up on this thread. Could really use some help?

Best wishes

Dan

**Comment by danjpalmer** [comment]
The reason we want to be able to run locally is to simply debug without having it post it to the App Store each time.

**Comment by beaufortfrancois** [comment]
Thank you Dan for raising this issue. I've just fixed it in https://github.com/GoogleChrome/chrome-app-samples/commit/474cbc711112cb43d6ce83deec013b46e4e4da02 and pushed an update to the Chrome Web Store at https://chrome.google.com/webstore/detail/pkbpddppnkjmlbgliipgmhjeialadokj

Please reopen if you're still experiencing this issue.
