### ISSUE TITLE
how to release socket resource used by chrome app when it is being closed

### ISSUE THREAD

**Issue by zhaojun12** [GoogleChrome/chrome-app-samples#407]
i create a chrome app using socket api to create a tcp server listening on port 8081 and connect with other server with tcp socket, but when i close the app, i find that the socket resource has not been released, for example, the listening port 8081 is still in used or the tcp socket is still alive.

so i want to ask is there a way to make sure that the socket resource has been released when the app is closed.

thanks.

**Comment by zhaojun12** [comment]
this does not happen all the time, but occasionally.

**Comment by zhaojun12** [comment]
i use chrome.sockets.tcp.create({},function(){}) to create tcp socket with persistent default value false.
if i open the app and close it quickly, the tcp socket resource will not be released.

**Comment by zhaojun12** [comment]
i find that 
1.if the chrome browser is not running, you start the chrome app and close it quickly, the socket resource is released immediately.
2.if the chrome browser is running, you start the chrome app and close it quickly, the socket resource is not released.

**Comment by zhaojun12** [comment]
here is the sample code, https://www.dropbox.com/s/kp3eaoh9wvmx1k5/chrome.zip?dl=0
this code only creates a tcp connection with 115.25.86.12 with dst port 8180 and sends nothing.
if the chrome browser is not running, the socket resource will be released immediately as you close the app;
but if the chrome browser is running, the socket resource will be released more or less 20 seconds later after you close the app.
This code is simple, i think if the code is sending something using tcp socket, the socket resource will not be released any more, just as the original app i have wrote. if you want to see the original code, i will share it with a link; but the code is a little messy. ^_^

**Comment by beaufortfrancois** [comment]
@krockot will know better than me what could happen exactly there.
I wonder if that's because `daemon.js` runs in the chrome app window versus in a background page. Do you mind trying and see if you notice any difference?

**Comment by zhaojun12** [comment]
I have tried `daemon.js` both in the chrome app window and in a background page, but there is no difference.

**Comment by krockot** [comment]
The lifetime of the socket is going to be tied to the lifetime of the app if you don't close the socket yourself.

If the browser is running when you close the last app window, the background page can still be kept alive for ~10 seconds. As long as the background page is alive, the app is alive and therefore the socket will remain open.

You could add a listener to the onClosed window event and explicitly close the socket there.

**Comment by zhaojun12** [comment]
@krockot yes, i have solved the problem as you said.
thank you all.
