### ISSUE TITLE
HID Barcode Scanner will not found

### ISSUE THREAD

**Issue by luxlux** [GoogleChrome/chrome-app-samples#415]
In the HID sample app on my Mac 10.9.5 (Chrome 47.0.2500.0 canary (64-bit)) it will not show HID barcode scanners. I have tried 2 different devices one from SYMBOL and one cheap china device "X500". Both are set to HID mode, and both work without installing a driver like a normal keyboard.

But both do not show up in the device list ot the HID SAMPLE APP (i.e. a calculator, which can be used as keypad will be shown.) So what's the reason for this?

ioreg -p IOUSB -w0 -l 
shows the following information for both devices:

The Symbol scanner (not shown):
```
+-o Symbol Bar Code Scanner@14100000  <class IOUSBDevice, id 0x10004104c, registered, matched, active, busy 0 (225 ms), retain 16>
        {
          "sessionID" = 422566515597343
          "iManufacturer" = 1
          "bNumConfigurations" = 1
          "idProduct" = 4608
          "bcdDevice" = 513
          "Bus Power Available" = 250
          "bMaxPacketSize0" = 8
          "USB Product Name" = "Symbol Bar Code Scanner"
          "iProduct" = 2
          "iSerialNumber" = 3
          "USB Address" = 1
          "bDeviceClass" = 0
          "bDeviceSubClass" = 0
          "locationID" = 336592896
          "IOUserClientClass" = "IOUSBDeviceUserClientV2"
          "PortNum" = 1
          "IOCFPlugInTypes" = {"9dc7b780-9ec0-11d4-a54f-000a27052861"="IOUSBFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
          "bDeviceProtocol" = 0
          "USB Vendor Name" = 
          "Device Speed" = 1
          "idVendor" = 1504
          "USB Serial Number" = "S/N:--REMOVED-- Rev:CBRPPMJB3"
          "Requested Power" = 200
          "IOGeneralInterest" = "IOCommand is not serializable"
          "Low Power Displayed" = No
        }
```
The Keypad (shown):
```
    | +-o USB Keypad@14210000  <class IOUSBDevice, id 0x100040d9d, registered, matched, active, busy 0 (680 ms), retain 18>
    |     {
    |       "sessionID" = 422492796001936
    |       "iManufacturer" = 0
    |       "bNumConfigurations" = 1
    |       "idProduct" = 25857
    |       "bcdDevice" = 533
    |       "Bus Power Available" = 250
    |       "bMaxPacketSize0" = 8
    |       "USB Product Name" = "USB Keypad"
    |       "iProduct" = 1
    |       "iSerialNumber" = 0
    |       "USB Address" = 22
    |       "bDeviceClass" = 0
    |       "locationID" = 337707008
    |       "bDeviceSubClass" = 0
    |       "IOUserClientClass" = "IOUSBDeviceUserClientV2"
    |       "PortNum" = 1
    |       "IOCFPlugInTypes" = {"9dc7b780-9ec0-11d4-a54f-000a27052861"="IOUSBFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
    |       "bDeviceProtocol" = 0
    |       "Device Speed" = 0
    |       "idVendor" = 4400
    |       "Requested Power" = 50
    |       "IOGeneralInterest" = "IOCommand is not serializable"
    |       "Low Power Displayed" = No
    |     }

```

Both devices work like a keyboard. So at the moment scanning works only if the needed app is in the focus and the courser is set to the correct place. But it should work also if the app is in background. so i guess i need this api, but possibly there is an other solution?

**Comment by reillyeon** [comment]
The chrome.hid API does not allow applications to open devices that look like keyboards because that would allow any Chrome App to function as a keylogger, which would be a Bad Thing™. If the device must function in keyboard mode (i.e. there isn't a raw USB or serial mode that would work with the chrome.usb or chrome.serial API) then the best you can do is register for key events on your application's <body> tag so that as long as the window is focused it will work.

**Comment by luxlux** [comment]
Thanks for your answer.

The device also allows to change it from HID mode to USB serial mode. But there is only a driver for doing all these serial settings for windows. Not for mac and even not for chromebooks on which the application should run in the end. Can the chrome.usb api function without a driver for the device?

**Comment by reillyeon** [comment]
Yes, the chrome.usb API is designed for the case where there is no driver for the device.

**Comment by luxlux** [comment]
Ok, so i will check this. thanks.
