### ISSUE TITLE
My device is not reconized by usb.getUserSelectedDevices. Is it normal?

### ISSUE THREAD

**Issue by noopole** [GoogleChrome/chrome-app-samples#417]
I'm trying to make a Chrome App connect to a USB Smart Card reader (HID Global OmniKey 3121, known as **CardMan 3121** form **OmniKey AG**).

I cannot connect to it while I can get a `Device` handle to my mouse or keyboard.
I've also put the device `vendorId` and `productId` in the `manifest.json` file, and the name was resolved successfully by Chrome (in **Extensions / [my App] / Details**).
With the OmniKey diagnostic too I can verifiy the my Card reader is OK and recognized by Windows (7).

Is it an expected behavior that not all the USB are listed by Chrome?

My phone (Nokia 925) is not reconized either when connected.

Maybe it's not the good place to post. Sorry in that case.

**Comment by reillyeon** [comment]
StackOverflow is a better place to ask support questions.

**Comment by noopole** [comment]
Maybe you should document your api. 
Anyway
