### ISSUE TITLE
Can't stop bluetooth discovery 

### ISSUE THREAD

**Issue by AndreasHeiberg** [GoogleChrome/chrome-app-samples#419]
I was writing a chrome app and needed to discover devices. It seemed that even though `chrome.bluetooth.stopDiscovery(function() {});` events for `onDeviceAdded` are called indefinitely

Assuming that something was wrong with my code I looked to your samples. It appears that you have the same problem. Even though stopDiscovery is called your event listener is being called indefinitely.

Is this the expected behaviour? Seems very strange to me.

Is there a fix for this?

**Comment by beaufortfrancois** [comment]
@AndreasHeiberg thanks for raising this issue.
You might want to file a bug at crbug.com/new so that the chromium team can have a look.
Please let me know when it's done.

@armansito Is that something you're aware of?

**Comment by beaufortfrancois** [comment]
@AndreasHeiberg For info, I was not able to reproduce the issue. Can you share steps to reproduce?

**Comment by jumoog** [comment]
click start sometimes if you click on stop nothings happend

https://www.youtube.com/watch?v=B-eaZbBd598&feature=youtu.be

**Comment by AndreasHeiberg** [comment]
If you can't reproduce it, let's assume that it was an abnormality until someone else raises it :)

I'm not currently working on that project anymore.
