### ISSUE TITLE
Apps in store broken, please update

### ISSUE THREAD

**Issue by jscissr** [GoogleChrome/chrome-app-samples#423]
The apps https://chrome.google.com/webstore/detail/serial-test/bdiclhdalonemjdeeaglackjgdboboem, https://chrome.google.com/webstore/detail/serial-control-signals/gmlopmidlcfikepbnklkochchhehjpak, and https://chrome.google.com/webstore/detail/adk-controller-sample/ieoiddehfkbacdideciijbdjfjegmpjo are broken, because of changes in the serial API. This was fixed in https://github.com/GoogleChrome/chrome-app-samples/commit/770d5032c41235909ae6fbff7bde6f7e8a40a2b8, but the apps haven't been updated in the Chrome Store since Oct 1, 2013.

**Comment by beaufortfrancois** [comment]
Thanks for raising this issue!

I've bumped manifest versions (https://github.com/GoogleChrome/chrome-app-samples/commit/a6c1236432697ac016ae58ccb6cafcd6cd1f08cf) and just updated all outdated serial app samples in the Web Store:

https://chrome.google.com/webstore/detail/serial-test/bdiclhdalonemjdeeaglackjgdboboem
https://chrome.google.com/webstore/detail/serial-control-signals/gmlopmidlcfikepbnklkochchhehjpak
https://chrome.google.com/webstore/detail/adk-controller-sample/ieoiddehfkbacdideciijbdjfjegmpjo
