### ISSUE TITLE
world clock example add feature does not work.

### ISSUE THREAD

**Issue by bhodgs01** [GoogleChrome/chrome-app-samples#424]
Hello,

When I click on the add button in the world clock, nothing happens.  I have tried entering city names like "london" or "tokyo" and that doesn't work either.  

Thank you so much for providing your code.  it is very helpful for me to learn. 

Thanks,

Blake

**Comment by beaufortfrancois** [comment]
Looking at what happens behind the scenes, the app gets a 401 (401 - Unauthorized: Access is denied due to invalid credentials.
) when reaching http://www.worldweatheronline.com/feed/tz.ashx?key=78b33b52eb213218120708&format=json&q=london

**Comment by beaufortfrancois** [comment]
I've fixed it (https://github.com/GoogleChrome/chrome-app-samples/commit/8be1373ba59ee0cb64b7083e0276d7d8f31cf8e0) and published a new version at https://chrome.google.com/webstore/detail/lhfiglpmnendbchimlikaeachppfonmm/

Thank you for raising this issue!

**Comment by bhodgs01** [comment]
Francois,

thank you very much for fixing it!  works great now.

I am following along with your code and trying to change the background of
the clock to the .svg attached.  How much would you charge to modify the
code so that the background is the image and remove the number for the
current time?  Let me know the price if you are willing.

Thanks,

Blake
ᐧ

On Mon, Jan 25, 2016 at 3:07 AM, François Beaufort <notifications@github.com
> wrote:

> I've fixed it (8be1373
> <https://github.com/GoogleChrome/chrome-app-samples/commit/8be1373ba59ee0cb64b7083e0276d7d8f31cf8e0>)
> and published a new version at
> https://chrome.google.com/webstore/detail/lhfiglpmnendbchimlikaeachppfonmm/
>
> Thank you for raising this issue!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleChrome/chrome-app-samples/issues/424#issuecomment-174442872>
> .
>



-- 
Blake Hodgson

**Comment by beaufortfrancois** [comment]
All you need is to change the config face color for that: https://github.com/GoogleChrome/chrome-app-samples/blob/ba78d3b1574631152b4b22f5b44ae748738fff97/samples/clock/clock.js#L5

**Comment by bhodgs01** [comment]
Francois,

Thanks for your help.  I had to change a few other things but I got the
image I wanted on there.  do you have a paypal account?  I'd like to
virtually buy you a beer.

There was a few hours today where the world clock was unresponsive.  I got
this error: Failed to load resource: the server responded with a status of
429 (Too Many Requests).  any idea what is causing this?

Thanks,

Blake
ᐧ

On Tue, Jan 26, 2016 at 1:38 AM, François Beaufort <notifications@github.com
> wrote:

> All you need is to change the config face color for that:
> https://github.com/GoogleChrome/chrome-app-samples/blob/ba78d3b1574631152b4b22f5b44ae748738fff97/samples/clock/clock.js#L5
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleChrome/chrome-app-samples/issues/424#issuecomment-174874751>
> .
>



-- 
Blake Hodgson

**Comment by beaufortfrancois** [comment]
No beer needed there ;)

I guess it's because the "key" used is only for the Free API. See https://developer.worldweatheronline.com/ 

You may want to use a "key" with the Premium API.
