### ISSUE TITLE
FileSystem sample isn't working

### ISSUE THREAD

**Issue by Shrest** [GoogleChrome/chrome-app-samples#428]
Hello,
        I was testing the sample of fileSystem of Chrome. But, when I open the web page & click on the button for choosing the file on my computer, nothing happens. I tried it on Chrome version 48+.

Not sure why its not working, am I missing something?

**Comment by beaufortfrancois** [comment]
Just to be sure, are you talking about https://chrome.google.com/webstore/detail/filesystem-access-sample/ehbhjpchdgepkgjhfkhpkjdbnljedllm/

Which platform are you running (win, macos, linux, cros)?

To debug this, you may want to open a tab to `chrome://inspect/#apps`, click on "Inspect" below "Filesystem Access Sample" and read logs there.

**Comment by Shrest** [comment]
I downloaded the files from here - https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/filesystem-access

and opened the html file in Chrome on a Windows 7 PC and it didn't work.

I will provide you the logs from "Inspect".

**Comment by Shrest** [comment]
Apologises for the delay, haven't got access to my computer last few days.
So, here are the observations in the console of Google Chrome when I try fileAccess sample:

on loading
-   uncaught ReferenceError:launchData is not defined                                   app.js:244

on clicking "Choose File" button
- uncaught TypeError:Cannot read property 'chooseEntry' of undefined         app.js:182

on clicking "Choose Directory" button
- uncaught TypeError:Cannot read property 'chooseEntry' of undefined        app.js:192

Do the above errors indicate anything?

**Comment by beaufortfrancois** [comment]
Here's how to load a Chrome App in developer mode: https://developer.chrome.com/extensions/getstarted#unpacked

**Comment by Shrest** [comment]
Thanks @beaufortfrancois It worked. The sample is great.

Is it possible to implement the same functionality using html & js (without extension)?

**Comment by beaufortfrancois** [comment]
It is not *yet* possible sadly.

**Comment by Shrest** [comment]
Im not into developing for web browsers. Curious about one thing - to access an API(for e.g.: fileSystem in Chrome) is using extensions the only method?

**Comment by beaufortfrancois** [comment]
You can use the soon-to-be-deprecated FileSystem API: http://www.html5rocks.com/en/tutorials/file/filesystem
