### ISSUE TITLE
loging g+ in chrome app

### ISSUE THREAD

**Issue by jitsingh89** [GoogleChrome/chrome-app-samples#431]
I am developing chrome app, in that i have to provide google+ login for users. I need username,image for login user. I am able to access this information using Identity sample.but i have requirement to login in same app. can anyone tell me any other way to login using g+.

**Comment by beaufortfrancois** [comment]
What do you mean by "same app"?

**Comment by jitsingh89** [comment]
same app means user use google api in chrome app to login for g+

**Comment by beaufortfrancois** [comment]
Look at https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/identity and check out https://developer.chrome.com/apps/app_identity. This should give you all you need to add G+ login in your chrome app.

**Comment by jitsingh89** [comment]
Hi where should I provide my login details. it is sending on browser.my requirement is after clicking on g+login button g+api should open in my app not on browser where i should provide email id password.after login successful i should get name,image city data.
