### ISSUE TITLE
chrome.identity.getAuthToken throws exception

### ISSUE THREAD

**Issue by woniesong92** [GoogleChrome/chrome-app-samples#436]
**Problem:**
`chrome.identity.getAuthToken()` function throws `{"message":"Authorization page could not be loaded."}` error and returns `undefined` for `token` when a Chrome **app runs in Korean locale**.

**Reproduction Steps:**
1. Run the [sample app](https://github.com/GoogleChrome/chrome-app-samples/blob/e347c538e8612aa3b0f90bde0fc721c4f0569125/samples/identity/README.md) and confirm that sign in works well.
2. Go to your language settings and change your language to Korean
3. Quit Chrome browser completely and open it again -- the browser should be in Korean now.
4. Run the [sample app](https://github.com/GoogleChrome/chrome-app-samples/blob/e347c538e8612aa3b0f90bde0fc721c4f0569125/samples/identity/README.md) and encounter `chrome.runtime.identity.getAuthToken: Authorization page could not be loaded` error.

<img width="454" alt="screen shot 2016-04-09 at 12 41 41" src="https://cloud.githubusercontent.com/assets/2935309/14402486/0fae83c4-fdec-11e5-990c-429eb2d426e6.png">

**Additional Info:**
I was having this problem with my Chrome app (quite puzzling because sign in doesn't work only in a certain locale) and I thought I did something wrong. I came here to look for the answer, and found out that the sample app is having the same problem. I tried the following things:

- Add the following domains to `permissions` in `manifest.js`

```
    "https://*.chromiumapp.org/*", "https://chromiumapp.org/",
    "https://*.apps.googleusercontent.com/", "https://apps.googleusercontent.com/",
    "https://apps.googleusercontent.com/", "https://*.chromiumapp.org/*/*",
    "*://*.google.com/*", "https://accounts.google.com/o/oauth2/v2/auth"
```

- Add `key` field in `manifest.js` so that App ID is the same for both production and development.
- Check that OAuth2 Client key has the right App ID.
- Use `chrome.identity.launchWebAuthFlow` in place of `chrome.identity.getAuthToken`
- Change the `'interactive': true` option to `false`
- Call `chrome.identity.getAuthToken({ 'interactive': true }` twice
- Call `chrome.identity.getAuthToken` in the callback of `chrome.identity.onSignInChanged`

None of the above worked.
I am happy to invite you to see my code on GitHub if that helps.

**Environment:**
- Chrome Version: 49.0.2623.110 (64-bit)
- OS: OS X El Capitan

**Can you**
- check if there's a problem with the API's redirect URL?
- tell me if I am doing something wrong?
- tell me if there's a workaround or a direct solution to this problem?

**Comment by beaufortfrancois** [comment]
Did you try https://chrome.google.com/webstore/detail/oficlfehfenioickohognhdhmmcpceil as well?

**Comment by beaufortfrancois** [comment]
Hello @woniesong92, 
Thanks for reporting this issue.

Can you file a bug as well at crbug.com/new and let me know so that I can triage it?

**Comment by woniesong92** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=602395

@beaufortfrancois do you possibly have an ETA for this?

**Comment by beaufortfrancois** [comment]
I've just pinged one person for your bug. Let's wait and see first ;)

**Comment by beaufortfrancois** [comment]
I'll close this issue and we'll continue conversation at http://crbug.com/602395

**Comment by woniesong92** [comment]
@beaufortfrancois the bug thread hasn't gotten response for 11 days. Do you think you could ping someone one more time? This bug is affecting a production app for me.

**Comment by beaufortfrancois** [comment]
Just cced another person at https://bugs.chromium.org/p/chromium/issues/detail?id=602395#c5

**Comment by woniesong92** [comment]
@beaufortfrancois Hey! It seems that the issue is still inactive. In my opinion, this bug could be significant as it globally prevents users who don't have `en` as their locale from signing into any Chrome app.

**Comment by woniesong92** [comment]
@beaufortfrancois Hey! I wanted to ping you one more time to see if I can get any kind of movement for this. This bug should be affecting a lot of users for any international chrome app that has an authentication.

**Comment by beaufortfrancois** [comment]
Thanks for reminding me!
I've pinged one more time.

**Comment by woniesong92** [comment]
H @beaufortfrancoisi! I was wondering the status of this. If you can use my help, I'd love to help as well :)

**Comment by beaufortfrancois** [comment]
Last update is now at https://bugs.chromium.org/p/chromium/issues/detail?id=602395#c5:  

```
courage@ was the owner of this API, however he doesn't work on it any more :(

Adding some other people who may be able to help.

Albert - I assume this also affects ChromeOS, maybe know of engineers who could help out?

**Comment by woniesong92** [comment]
@beaufortfrancois it's been quite some time since that inquiry 😢 
Will someone take a look at it anytime soon?

**Comment by beaufortfrancois** [comment]
Your best bet is to follow https://bugs.chromium.org/p/chromium/issues/detail?id=602395#c5 now.

**Comment by wasimxe** [comment]
If youtube is blocked at your network, you will get error Authorization page could not be loaded.

**Comment by darrylblake** [comment]
> when a Chrome app runs in Korean locale.

Interesting! Is this the only locale that it happens for that you know of?
