### ISSUE TITLE
Usb label printer label orientation

### ISSUE THREAD

**Issue by enyachoke** [GoogleChrome/chrome-app-samples#437]
Am try to use the sample usb printer app with a dymo label writer 450 turbo. The printing works but the orientation is wrong how can I fix that. 
![20160420_142248](https://cloud.githubusercontent.com/assets/1908926/14672953/ad05aace-0703-11e6-90c5-ad6be071119c.jpg)

Am using 2.25 X  1.25 in labels.

**Comment by reillyeon** [comment]
Unfortunately this is not a support forum for this model of printer. The app is distributed only as a demo for the USB API. We know nothing about this printer.
