### ISSUE TITLE
One-time payment sample app not found

### ISSUE THREAD

**Issue by MGTHEBOSS** [GoogleChrome/chrome-app-samples#438]
One-time payment documentation for chrome apps is available here: [One-Time Payments](https://developer.chrome.com/webstore/one_time_payments). At the bottom of the page, there is a link to the source code of a simple chrome app that demonstrates how to use the Chrome Web Store Licensing API: [Sample Chrome App Source Code](https://github.com/GoogleChrome/chrome-app-samples/tree/master/one-time-payment). It's giving a 404 error. I would like to know where I can view a working sample which demonstrates one-time payment with free trial.

**Comment by beaufortfrancois** [comment]
Here it is: https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/one-time-payment
