### ISSUE TITLE
Where is the button for "Publishing to test accounts"?

### ISSUE THREAD

**Issue by MGTHEBOSS** [GoogleChrome/chrome-app-samples#441]
I want to publish an extension to test accounts to test the payment flow, I have added one tester account in the "Edit your tester accounts" section on the Dashboard. I do not see the "Publish to test accounts" button. Where is it?

**Comment by beaufortfrancois** [comment]
According to http://stackoverflow.com/questions/11098325/how-to-publish-new-version-of-chrome-extension-only-to-testers,_ The button "Publish to tester accounts" is only on the unpublished extension._

**Comment by MGTHEBOSS** [comment]
Documentation needs to improve. What you are saying cannot be correct because I did not see the button when the extension was in unpublished state and I just added one test account. In the mentioned question, which has no accepted answers, there is an answer from `Fyresoul` which says: "The way that the dashboard is currently set up you would have to un-publish your current application before you can publish it to the test accounts." I unpublished the extension and did not see the "Publish to test accounts"  button. Also, the second answer, which is from `Lukisjama` (the person who asked the question), says: "... right now there is a option to publish the new version just to the testers." Which version is active at the moment?

**Comment by beaufortfrancois** [comment]
Here's the message I get from my own Chrome Webstore Item detail page:

![screenshot 2016-05-02 at 1 41 03 pm](https://cloud.githubusercontent.com/assets/634478/14953616/88252dd0-106b-11e6-89da-aabf6ec40b3d.png)

**Comment by MGTHEBOSS** [comment]
So, I need to select Private, and click on "Publish changes"?
![visibility](https://cloud.githubusercontent.com/assets/3612991/14953737/06b0803c-108a-11e6-9f0b-b1ebaf732a1a.png)

**Comment by beaufortfrancois** [comment]
Yup!

**Comment by ken107** [comment]
In my case I have an extension with active users that I want to test in-app payments.  I definitely don't want to unpublish or even make it private.  Turns out the way is to create a NEW extension and use it for testing.

**Comment by yogendrakumar96** [comment]
what is the next case after published to testers as I want to give my extension to more people ?
