### ISSUE TITLE
Questions regarding Chrome Web Store API 

### ISSUE THREAD

**Issue by MGTHEBOSS** [GoogleChrome/chrome-app-samples#442]
According to [Caching the response](https://developer.chrome.com/webstore/one_time_payments#cache-response), "To improve the performance and avoid running into rate limits, you should cache the license data locally using the chrome.storage.sync API". When I tried to search the limit I did not find any official information. A search in Google API Explorer led to a dead end.
![cws api missing](https://cloud.githubusercontent.com/assets/3612991/14987626/f0744fee-116d-11e6-8560-1ad6cea51603.png)
In a question ([How to request a Quota increase for Chrome Web Store API](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/B0vro7BZllo), the quota is mentioned to be 10,000 requests/day, is this correct? I would also like an answer to the question.
Is there any code sample which shows caching the license data locally using the chrome.storage.sync API?

**Comment by beaufortfrancois** [comment]
I'm able to see the Chrome Web Store API at https://console.developers.google.com/apis/api/chromewebstore/overview

![screenshot 2016-05-04 at 9 15 20 am](https://cloud.githubusercontent.com/assets/634478/15007371/bf4d1908-11d8-11e6-91bb-35b869f5788e.png)

When enabling it, I get access to all quotas:

![screenshot 2016-05-04 at 9 16 34 am](https://cloud.githubusercontent.com/assets/634478/15007395/ef7c67c8-11d8-11e6-91be-38ce6c23bed9.png)
