### ISSUE TITLE
Various BLE errors

### ISSUE THREAD

**Issue by PENDOnl** [GoogleChrome/chrome-app-samples#444]
Hi,

thanks for the work so far, however, I don't seem to be able to get any of the BLE examples working. I'm using a Polar H7 heartrate device which I'd like to read from Chrome (v50.0.2661) but these are the things I run in to:

(1) I am able to find the HR device when searching for devices, however, I don't seem to be able to stop discovering for device. 

(2) When I select a device it still says (and logs): no device selected

I tweaked the files a little bit to always show multiple devices when something is found (to trigger the connect function), this results in another error:

Cannot connect to device "ad:dr:es:s" - In progress

I've got no clue what the "In Progress" message means, hard to find anything on it using a search engine. I tried to download the extionsion linked in the readme but that won't work either.

Any ideas? Thanks for thinking along.

**Comment by beaufortfrancois** [comment]
Which platform are you running?
Chrome OS, Mac OS, Windows?

**Comment by PENDOnl** [comment]
Chrome 50.0.2661 on Mac 10.11.4 (OS X El Capitan)

**Comment by beaufortfrancois** [comment]
I believe that the BLE implementation is not complete on Mac OS X.
You may want to look at https://github.com/WebBluetoothCG/web-bluetooth/blob/gh-pages/implementation-status.md#chrome to follow work in progress in this area.

**Comment by beaufortfrancois** [comment]
See https://developer.chrome.com/apps/bluetoothLowEnergy

**Comment by beaufortfrancois** [comment]
No problem! Good luck!

**Comment by PENDOnl** [comment]
I installed ChromeOS using Parallels on my mac, but this does gives the error that I need at least Chromium version 37, but the latest version according to the OS is v32. Any ideas?

**Comment by beaufortfrancois** [comment]
Chrome OS is now version 50.
You might want to find a more recent image there.

**Comment by PENDOnl** [comment]
True, my bad! I thought parallels would've fetched the latest build. I'm getting a little bit further than last time, however still some little bugs. I'll update the issue as soon as I know more.
