### ISSUE TITLE
usb-label-printer not working

### ISSUE THREAD

**Issue by atvvarna** [GoogleChrome/chrome-app-samples#445]
Hello,
I've just installed it and changed 
var vendorId = 0x0922h;
var productId = 0x0022;
To match my Dymo Twin Turbo 450 but if I click print nothing happened.

Any help will be appreciated.

Regards,
Alex

**Comment by reillyeon** [comment]
That is a different model than this code was originally tested with. The purpose of this example is to demo the chrome.usb API, not provide a working driver for all of Dymo's label printers. If you would like to start a new project to expand the set of printers supported you are welcome to use this demo as a starting point.
