### ISSUE TITLE
scanning with bluetoothLowEnergy

### ISSUE THREAD

**Issue by DevAndrew** [GoogleChrome/chrome-app-samples#448]
I saw issue
https://github.com/GoogleChrome/chrome-app-samples/issues/350

Quote from this issue:
> Bluetooth 4.0 (BLE) provides the ability to scan nearby devices based on a service UUID, and then connect and query characteristics and descriptors.

I need to find nearby BLE tags without services. Is that possible?

**Comment by beaufortfrancois** [comment]
It is NOT possible with the `chrome.bluetooth.startDiscovery` method.

I would recommend you have a look the experimental Web Bluetooth API which lets you scan by device name and device name prefix. A sample can be found at https://googlechrome.github.io/samples/web-bluetooth/device-info.html. 

Check out https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web to learn more about this API available (for now) on Chrome OS, Chrome for Android, Chrome for Linux. macOS and Windows support are coming as well: https://github.com/WebBluetoothCG/web-bluetooth/blob/gh-pages/implementation-status.md#chrome

**Comment by DevAndrew** [comment]
Thanks. I checked these links. My main targets macOS and Windows... I'll be waiting.

**Comment by beaufortfrancois** [comment]
For info, you can already scan and connect to BLE devices on Chrome Canary for macOS (chrome.com/canary). Getting services & characteristics is coming.
