### ISSUE TITLE
Constantly receiving: "An unexpected error has occurred. Please try again later."

### ISSUE THREAD

**Issue by vondiplo** [GoogleChrome/chrome-app-samples#451]
when I attempt to purchase using this endpoint - `google.payments.inapp.buy`
I get the following error -

> An unexpected error has occurred. Please try again later.

When I look at the console of the prompted paymet screen I see that there's a failed attempt to call a service at url -

> https://224.32.32.55/29753 Failed to load resource: net::ERR_ADDRESS_UNREACHABLE

It used to work in the past and stopped. What could be causing this?

**Comment by beaufortfrancois** [comment]
This repository is about samples.
You might want to file an issue at crbug.com/new
