### ISSUE TITLE
frameless window: titlebar not immediately draggable

### ISSUE THREAD

**Issue by ionous** [GoogleChrome/chrome-app-samples#454]
**Issue:** Custom titlebar not immediately draggable

**Repro steps:**
Goggle Chrome - Version 52.0.2743.116 (64-bit)
OS X Yosemite 10.10.5

- After starting the app, check one of the boxes to enable a titlebar.
- Dragging the window via the titlebar does not work.
- Without exiting the sample, switch to a different application then switch back.
- Now dragging the window via the titlebar works.
- Enable a second titlebar and the new titlebar is not draggable; the old one still is.
- Switch to a different application then switch back: both titlebars are now draggable.
- The titlebars stay draggable across multiple enable/disable changes, until you disable a titlebar, switch to a different application, and then switch back.

( Note:  This may be related to the web store [comment](https://chrome.google.com/webstore/detail/frameless-window-sample/hjjdaddngnaofnfjpajdcbdmkegiakec/reviews) "-webkit-app-region: drag; doesn't work"  )
...
I can make the titlebars work as expected by changing the code to hide and show the window after the titlebar has been changed. At the the end of `frameless_window.js` `initCheckbox()` adding:

    var win= chrome.app.window.current();
    win.hide();
    win.show();`

**Comment by reillyeon** [comment]
This sounds like a bug in Chrome. Please file a bug in the [Chrome bug tracker](https://crbug.com).
