### ISSUE TITLE
Problem connectin to USB device on Windows

### ISSUE THREAD

**Issue by ftaiolivista** [GoogleChrome/chrome-app-samples#464]
Hi.

I'm developing an app connecting to a USB microscope (it's a webcam with some led mounted).
The app can use <video> to show live video from webcam and I must control LED with simple USB commands. On OSX all seems to work good. 
I can live display video and use USB command to turn on/off leds but on Windows the APP cannot found the device to send SEND USB commands, the live video show good but usb fail to found the device to control led.

Calling chrome.usb.getUserSelectedDevices() on windows don't find the device but the device is listed in windows under System Devices under image acquisition.

Can anyone help me?

App permission:

"permissions": [
    "videoCapture",
    "usb",
    {"usbDevices": [{"vendorId": 41320, "productId": 2162}]}
  ]

**Comment by reillyeon** [comment]
The fact that the device is listed under "Image Acquisition" is why Chrome can't detect the device. Chrome needs the device to be using the winusb.sys driver or else Windows won't let Chrome send raw USB commands. This isn't an issue on macOS and Linux. If the device is controlled by winusb.sys it will appear under "USB devices".

**Comment by FbN** [comment]
Is there a way to have the device controlled by winusb.sys e videousb.sys at the same time?

**Comment by reillyeon** [comment]
Only if the device has two separate interfaces. Then you can write a driver INF file that loads winusb.sys specifically for the non-video interface. If the device is not composite then there's no way that I am aware of to do it.

**Comment by FbN** [comment]
Hi @reillyeon ,

Yes the device got two interfaces, take a look at this device description 
![screenshot_20161217_103155](https://cloud.githubusercontent.com/assets/489583/21285861/b9e7cb1a-c444-11e6-9863-5fae678daa88.png)


Any sample of INF file of that kind? 

I have developed a complex chrome app to use the device to find that does not work on windows but only on linux/osx. If you can help me you are my Savior :)

**Comment by reillyeon** [comment]
Unfortunately while the device has two interfaces in this case they are part of the same "function" which means that the videousb.sys driver loads over both of them.

**Comment by FbN** [comment]
Ouhhh :(

On linux and OSX I managed to connect to the device wile it's working as
webcam using endpoint instead of interface setted in recipient. But on
windows there is no hope so :(

2017-01-20 17:13 GMT+01:00 Reilly Grant <notifications@github.com>:
