### ISSUE TITLE
(Windows 10) Chrome.hid.getDevices doesn't work if the device is a hid usb keyboard

### ISSUE THREAD

**Issue by danicomas** [GoogleChrome/chrome-app-samples#465]
Could you change the filter to detect the hid devices? I have download the hidapi project and in the hid_enumerate function in hid.c you can remove the line ```if (strcmp(driver_name, "HIDClass")``` (https://github.com/signal11/hidapi/issues/290) and after that the device is detected and working well. Could you do something to solve that? You could do an only search via vendorid, serialnumber... Or including the same filter than usb class (the chrome.usb.getDevices detects the device well) ... Or open the device via path hid_open_path (http://www.signal11.us/oss/hidapi/hidapi/doxygen/html/group__API.html)? @reillyeon @beaufortfrancois

**Comment by reillyeon** [comment]
This restriction exists on purpose to prevent an application using chrome.hid from acting as a keylogger.

**Comment by danicomas** [comment]
Your explanation makes no sense. Could you elaborate it more? A keylogger can do it now too. They can access via Chrome.usb.
What is the difference in open a device via path if you are the only user knows the path. I can understand if you want don't show all devices (probably this makes no sense for reasonable problems). What do you think @reillyeon ? Any solution should exist and I think that the last one could be.

**Comment by danicomas** [comment]
Opened a request to add aa function to connect via local device path as do other hid devices https://github.com/GoogleChrome/chrome-app-samples/issues/466.

**Comment by reillyeon** [comment]
An app cannot use chrome.usb to open a HID device.

**Comment by danicomas** [comment]
Win10 should be using the KBHid.sys which is inside of HIDClass.sys and could cause the wrong enumerate device because the api only filter by HIDClass. See this diagram:
https://msdn.microsoft.com/en-us/windows/hardware/drivers/hid/keyboard-and-mouse-hid-client-drivers

In this case I think the child classes should be added in the filter too @reillyeon.

**Comment by danicomas** [comment]
I have found that if you are doing ```strcmp(driver_name, "HIDClass")```... In windows 10 the driver name is the name instead than the driver class.
