### ISSUE TITLE
(Request) Chrome.hid.connect − add api function to connect via device path.

### ISSUE THREAD

**Issue by danicomas** [GoogleChrome/chrome-app-samples#466]
Some hid libs has a function to connect the device via path (hid_open_path http://www.signal11.us/oss/hidapi/hidapi/doxygen/html/group__API.html). It could solve related problems to some hid devices and keeping the restriction to keyloggers because they wouldn't know the device (you should keep the hid getDevices as working now or supress it due to show all the devices could be a big vulnerability I think that could be a problem in this moment)

@reillyeon

**Comment by reillyeon** [comment]
Device paths are rather guessable.

**Comment by reillyeon** [comment]
The correct issue tracker for filing issues against the Chrome Apps APIs is crbug.com.
