### ISSUE TITLE
Is the Serial API going to stick around?

### ISSUE THREAD

**Issue by rclai** [GoogleChrome/chrome-app-samples#469]
Since your guys are [moving away from Chrome Apps](http://blog.chromium.org/2016/08/from-chrome-apps-to-web.html), what's going to happen to the Serial, Bluetooth and USB APIs? Will they be available in Extensions?

**Comment by reillyeon** [comment]
From the article: 

> We will be removing support for packaged and hosted apps from Chrome on Windows, Mac, and Linux over the next two years. All types of Chrome apps will remain supported and maintained on Chrome OS for the foreseeable future.

This means that the Serial, Bluetooth and USB APIs will remain available on Chrome OS.

Have you looked into the Web Bluetooth or WebUSB APIs?

**Comment by rclai** [comment]
Oh I see. Will these Web APIs be available for Chrome Extensions?

**Comment by reillyeon** [comment]
I believe that Web Bluetooth already works in Chrome Extensions. WebUSB does not but that's a bug caused by some missing UI pieces.

**Comment by beaufortfrancois** [comment]
I confirm that Web Bluetooth works great in Chrome Extensions already.
See https://developers.chrome.com/apps/migration

> Q: My app uses chrome.bluetooth/chrome.usb to talk to a Bluetooth/USB device. Can this be done on the open web?
> 
> There are now proposals for new Web Bluetooth and WebUSB standards, designed to allow this functionality.
>

**Comment by rclai** [comment]
Cool, looking forward to seeing WebUSB make it to Extensions.
